// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.10.1
// source: examples/examples.proto

package examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shouldn't trust client-supplied ELO but this is just an example...
type MatchUsingElo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elo float32 `protobuf:"fixed32,1,opt,name=elo,proto3" json:"elo,omitempty"`
}

func (x *MatchUsingElo) Reset() {
	*x = MatchUsingElo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_examples_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchUsingElo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchUsingElo) ProtoMessage() {}

func (x *MatchUsingElo) ProtoReflect() protoreflect.Message {
	mi := &file_examples_examples_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchUsingElo.ProtoReflect.Descriptor instead.
func (*MatchUsingElo) Descriptor() ([]byte, []int) {
	return file_examples_examples_proto_rawDescGZIP(), []int{0}
}

func (x *MatchUsingElo) GetElo() float32 {
	if x != nil {
		return x.Elo
	}
	return 0
}

// What ELO range is acceptable?
type EloRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range float32 `protobuf:"fixed32,1,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *EloRange) Reset() {
	*x = EloRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_examples_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EloRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EloRange) ProtoMessage() {}

func (x *EloRange) ProtoReflect() protoreflect.Message {
	mi := &file_examples_examples_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EloRange.ProtoReflect.Descriptor instead.
func (*EloRange) Descriptor() ([]byte, []int) {
	return file_examples_examples_proto_rawDescGZIP(), []int{1}
}

func (x *EloRange) GetRange() float32 {
	if x != nil {
		return x.Range
	}
	return 0
}

var File_examples_examples_proto protoreflect.FileDescriptor

var file_examples_examples_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x69, 0x6e,
	0x67, 0x45, 0x6c, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x65, 0x6c, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x45, 0x6c, 0x6f, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x61, 0x69, 0x72, 0x6c, 0x79, 0x53, 0x61, 0x64,
	0x50, 0x61, 0x6e, 0x64, 0x61, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x2d, 0x62, 0x75, 0x74, 0x2d, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x67, 0x6f, 0x74, 0x2d, 0x73, 0x68,
	0x72, 0x65, 0x6b, 0x65, 0x64, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_examples_proto_rawDescOnce sync.Once
	file_examples_examples_proto_rawDescData = file_examples_examples_proto_rawDesc
)

func file_examples_examples_proto_rawDescGZIP() []byte {
	file_examples_examples_proto_rawDescOnce.Do(func() {
		file_examples_examples_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_examples_proto_rawDescData)
	})
	return file_examples_examples_proto_rawDescData
}

var file_examples_examples_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_examples_proto_goTypes = []interface{}{
	(*MatchUsingElo)(nil), // 0: examples.MatchUsingElo
	(*EloRange)(nil),      // 1: examples.EloRange
}
var file_examples_examples_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_examples_proto_init() }
func file_examples_examples_proto_init() {
	if File_examples_examples_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_examples_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchUsingElo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_examples_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EloRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_examples_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_examples_proto_goTypes,
		DependencyIndexes: file_examples_examples_proto_depIdxs,
		MessageInfos:      file_examples_examples_proto_msgTypes,
	}.Build()
	File_examples_examples_proto = out.File
	file_examples_examples_proto_rawDesc = nil
	file_examples_examples_proto_goTypes = nil
	file_examples_examples_proto_depIdxs = nil
}
